Repository stroeer/tapir, pull requests merged in 2020-12, with the labels that each got.

#124 removed deprecated index of Assets
  stroeer/core/v1/article.proto
Labels: ✋ do not merge, 🎁 API, 💥 breaking change

#125 use an enum for the state of an article
  stroeer/core/v1/article.proto
Labels: ✋ do not merge, 🎁 API, 💥 breaking change

#126 streamlined APIs in page package
  node/__tests__/services.test.ts
  stroeer/page/article/v1/api_config_http.yaml
  stroeer/page/article/v1/article_page.proto
  stroeer/page/article/v1/article_page_service.proto
  stroeer/page/section/v1/section_page.proto
  stroeer/page/section/v1/section_page_service.proto
  stroeer/pages/article/v1/article.proto
  stroeer/pages/article/v1/article_service.proto
Labels: ✋ do not merge, 🎁 API, 💥 breaking change

#119 new protoc image with latest dependencies using protoc 3.14.0
  Makefile
Labels: ✋ do not merge, 💅 enhancement, 🔄 dependencies

#123 Widths for changed designs
  stroeer/page/section/v1/section_page.proto
Labels: 🎁 API, 💥 breaking change
