Repository stroeer/tapir, pull requests merged in 2020-09, with the labels that each got.

#51 bugfix / reference to docker image
  Makefile
Labels: 💅 enhancement

#52 bugfix / go protoc version compatibility
  Dockerfile
  build_docker.sh
  go/go.mod
  go/go.sum
  go/stroeer/core/v1/core_article_service_grpc.pb.go
  go/stroeer/coremedia/v1/curation_service_grpc.pb.go
  go/stroeer/web/article/v1/web_article_service.pb.go
  go/stroeer/web/article/v1/web_article_service_grpc.pb.go
  go/stroeer/web/section/v1/web_section_service_grpc.pb.go
Labels: 🐛 bug

#46 chore: version bump + @grpc/grpc-js
  Makefile
  README.md
  build_docker.sh
  node/package-lock.json
  node/package.json
Labels: 💥 breaking change, 🔄 dependencies
