Repository stroeer/tapir, pull requests merged in 2020-10, with the labels that each got.

#49 feature / docker release action
  .github/workflows/docker-release.yml
Labels: 💅 enhancement

#56 Mandatory root fields and strongly typed dates
  go/stroeer/core/v1/article.pb.go
  go/stroeer/core/v1/core_article_service.pb.go
  go/stroeer/coremedia/v1/curated_article.pb.go
  go/stroeer/coremedia/v1/curation_service.pb.go
  go/stroeer/web/article/v1/web_article.pb.go
  go/stroeer/web/article/v1/web_article_service.pb.go
  go/stroeer/web/section/v1/web_section_service.pb.go
  java/build.gradle
  java/src/test/java/de/stroeer/article/v1/ArticleTest.java
  stroeer/core/v1/article.proto
  stroeer/pages/article/v1/article.proto
  stroeer/pages/article/v1/article_service.proto
  stroeer/pages/section/v1/web_section_service.proto
Labels: 🎁 API, 💅 enhancement, 💥 breaking change

#58 fix(node): update tests
  node/__tests__/services.test.ts
Labels: 🐛 bug

#63 migrate "web" to "pages"
  go/generator_test.go
  go/stroeer/pages/section/v1/section_page.pb.go
  go/stroeer/pages/section/v1/section_service.pb.go
  go/stroeer/web/article/v1/web_article.pb.go
  go/stroeer/web/article/v1/web_article_service.pb.go
  go/stroeer/web/article/v1/web_article_service_grpc.pb.go
  go/stroeer/web/section/v1/web_section_service.pb.go
  go/stroeer/web/section/v1/web_section_service_grpc.pb.go
  stroeer/pages/section/v1/section_page.proto
  stroeer/pages/section/v1/section_service.proto
  stroeer/web/article/v1/web_article.proto
  stroeer/web/article/v1/web_article_service.proto
  stroeer/web/section/v1/web_section_page.proto
  stroeer/web/section/v1/web_section_service.proto
Labels: 🎁 API, 💥 breaking change

#80 Added new content sub types
  java/build.gradle
  stroeer/core/v1/article.proto
Labels: 🎁 API

#83 Curation Service for Homepage Version Zero
  go/stroeer/core/v1/article.pb.go
  go/stroeer/core/v1/core_article_service.pb.go
  go/stroeer/core/v1/core_article_service_grpc.pb.go
  go/stroeer/coremedia/v1/curated_article.pb.go
  go/stroeer/coremedia/v1/curated_stage.pb.go
  go/stroeer/coremedia/v1/curation_service.pb.go
  go/stroeer/coremedia/v1/curation_service_grpc.pb.go
  go/stroeer/pages/article/v1/article.pb.go
  go/stroeer/pages/article/v1/article_service.pb.go
  go/stroeer/pages/article/v1/article_service_grpc.pb.go
  go/stroeer/pages/section/v1/section_page.pb.go
  go/stroeer/pages/section/v1/section_service.pb.go
  go/stroeer/pages/section/v1/section_service_grpc.pb.go
  stroeer/coremedia/v1/curated_article.proto
  stroeer/coremedia/v1/curated_stage.proto
  stroeer/coremedia/v1/curation_service.proto
Labels: 🎁 API, 💥 breaking change

#65 Author message specification
  go/stroeer/core/v1/article.pb.go
  stroeer/core/v1/article.proto
Labels: 🎁 API, 💥 breaking change

#86 Stage specification
  go/stroeer/core/v1/article.pb.go
  go/stroeer/coremedia/v1/curated_stage.pb.go
  go/stroeer/coremedia/v1/curation_service.pb.go
  go/stroeer/coremedia/v1/curation_service_grpc.pb.go
  go/stroeer/pages/article/v1/article_service.pb.go
  go/stroeer/pages/section/v1/section_page.pb.go
  stroeer/pages/section/v1/section_page.proto
Labels: 🎁 API, 💥 breaking change

#97 added API guidelines and polished the docs in general
  README.md
  docs/tapir.png
Labels: 📖 documentation
