Repository stroeer/tapir, pull requests merged in 2020-08, with the labels that each got.

#40 chore(node): version bump
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  node/package-lock.json
  node/package.json
Labels: 💅 enhancement, 🔄 dependencies

#38 enhanced dockerfile for generating go
  .github/workflows/pull-request.yml
  Dockerfile
  Makefile
  README.md
  go/generator_test.go
  go/stroeer/core/v1/article.pb.go
  go/stroeer/core/v1/core_article_service.pb.go
  go/stroeer/core/v1/core_article_service_grpc.pb.go
  go/stroeer/coremedia/v1/curated_article.pb.go
  go/stroeer/coremedia/v1/curation_service.pb.go
  go/stroeer/coremedia/v1/curation_service_grpc.pb.go
  go/stroeer/web/article/v1/web_article.pb.go
  go/stroeer/web/article/v1/web_article_service.pb.go
  go/stroeer/web/article/v1/web_article_service_grpc.pb.go
  go/stroeer/web/section/v1/web_section_service.pb.go
  go/stroeer/web/section/v1/web_section_service_grpc.pb.go
Labels: 💅 enhancement

#44 feat(node): remove test
  node/__tests__/models.test.ts
Labels: 💅 enhancement

#43 Draft for self contained body
  stroeer/core/v1/article.proto
  stroeer/web/article/v1/web_article.proto
  stroeer/web/article/v1/web_article_service.proto
Labels: 🎁 API
