Repository stroeer/tapir, pull requests merged in 2020-11, with the labels that each got.

#101 Updated dependencies
  go/go.mod
  go/go.sum
  java/build.gradle
  java/gradle/wrapper/gradle-wrapper.jar
  java/gradle/wrapper/gradle-wrapper.properties
  java/gradlew
  java/gradlew.bat
  java/src/test/java/de/stroeer/article/v1/ArticleTest.java
  node/package-lock.json
  node/package.json
Labels: 🔄 dependencies

#107 grpc-gateway tooling
  Dockerfile
  Makefile
  README.md
  buf.yaml
  go/go.mod
  go/go.sum
  go/stroeer/pages/article/v1/article_service.pb.gw.go
  go/tools.go
  stroeer/pages/article/v1/api_config_http.yaml
Labels: go, 🎁 API, 💅 enhancement

#111 Documented core.Article proto messages
  stroeer/core/v1/article.proto
Labels: ❓question, 🆘 help wanted, 📖 documentation

#117 chore(node): dependencies
  node/package-lock.json
  node/package.json
Labels: 🔄 dependencies

#120 chore(node): bump dependencies for protoc 3.14.0
  node/package-lock.json
  node/package.json
Labels: 🔄 dependencies
