Repository stroeer/tapir, pull requests merged in 2021-06, with the labels that each got.

#236 breaking(api): section data rework
  go/stroeer/page/section/v1/section_page.pb.go
  go/stroeer/page/section/v1/section_page_service_grpc.pb.go
  stroeer/page/section/v1/section_page.proto
  stroeer/page/section/v1/section_page_service.proto
Labels: 🎁 API, 💥 breaking change

#234 breaking(node): dependency instead of peerDependency
  node/package-lock.json
  node/package.json
Labels: 💥 breaking change, 🔄 dependencies

#237 chore: protoc 3.17.3
  Makefile
  go/stroeer/core/v1/article.pb.go
  go/stroeer/core/v1/core_article_service.pb.go
  go/stroeer/core/v1/shared.pb.go
  go/stroeer/coremedia/v1/curated_stage.pb.go
  go/stroeer/coremedia/v1/curation_service.pb.go
  go/stroeer/fragment/v1/stage_service.pb.go
  go/stroeer/page/article/v1/article_page.pb.go
  go/stroeer/page/article/v1/article_page_service.pb.go
  go/stroeer/page/section/v1/section_page.pb.go
  go/stroeer/page/section/v1/section_page_service.pb.go
Labels: docker, 🔄 dependencies

#235 breaking: simple enums
  buf.yaml
  go/stroeer/core/v1/article.pb.go
  java/src/test/java/de/stroeer/article/v1/ArticleTest.java
  stroeer/core/v1/article.proto
Labels: 🎁 API, 💥 breaking change
