Repository stroeer/tapir, pull requests merged in 2021-08, with the labels that each got.

#260 chore(node): version bumps + security fix
  node/package-lock.json
  node/package.json
Labels: 🔄 dependencies

#267 feat(node): bump versions + move @types/google-protobuf to dep list
  node/package-lock.json
  node/package.json
Labels: 🔄 dependencies, javascript

#266 [BREAKING] Stages on ArticlePages and Reference facelift
  go/stroeer/core/v1/shared.pb.go
  go/stroeer/fragment/v1/stage_service.pb.go
  go/stroeer/page/article/v1/article_page.pb.go
  go/stroeer/page/section/v1/section_page.pb.go
  go/stroeer/page/stage/v1/stage.pb.go
  stroeer/core/v1/shared.proto
  stroeer/fragment/v1/stage_service.proto
  stroeer/page/article/v1/article_page.proto
  stroeer/page/section/v1/section_page.proto
  stroeer/page/stage/v1/stage.proto
Labels: 💅 enhancement, 💥 breaking change
