Repository stroeer/tapir, pull requests merged in 2021-02, with the labels that each got.

#150 feat(model): shared page data
  stroeer/core/v1/article.proto
  stroeer/core/v1/shared.proto
  stroeer/page/section/v1/section_page.proto
Labels: 🎁 API, 💥 breaking change

#140 chore(node): node 14 LTS
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  node/.nvmrc
  node/package.json
Labels: 🔄 dependencies

#156 chore(node): version bump
  node/package-lock.json
  node/package.json
Labels: 🔄 dependencies

#157 bumped java and go dependencies
  go/go.mod
  go/go.sum
  java/build.gradle
  java/gradle/wrapper/gradle-wrapper.properties
Labels: 🔄 dependencies

#155 feat: Reference
  stroeer/core/v1/article.proto
  stroeer/core/v1/shared.proto
  stroeer/page/section/v1/section_page.proto
Labels: 🎁 API, 💥 breaking change

#161 Refactoring: element relations
  stroeer/core/v1/article.proto
Labels: 🎁 API, 💥 breaking change

#160 Refactoring: Timestamps
  stroeer/core/v1/article.proto
Labels: 🎁 API, 💥 breaking change

#163 added esi and citation element types
  stroeer/core/v1/article.proto
Labels: 🎁 API

#165 fix: non repeated sections
  stroeer/page/section/v1/section_page.proto
Labels: 🎁 API, 💥 breaking change
