Repository stroeer/tapir, pull requests merged in 2021-09, with the labels that each got.

#274 added `State.DELETED`
  .github/workflows/fundoc.yml
  .gitignore
  Makefile
  docs_resources/introduction.md
  fundoc.json
  go/stroeer/core/v1/article.pb.go
  go/stroeer/core/v1/shared.pb.go
  stroeer/core/v1/article.proto
Labels: 🎁 API

#276 refactor(go): externalized generated go module to separate repository
  .github/workflows/packages.yml
  .github/workflows/pull-request.yml
  .gitignore
  Makefile
  README.md
  go/README.md
  go/generator_test.go
  go/go.mod
  go/go.sum
  go/stroeer/core/v1/article.pb.go
  go/stroeer/core/v1/core_article_service.pb.go
  go/stroeer/core/v1/core_article_service_grpc.pb.go
  go/stroeer/core/v1/shared.pb.go
  go/stroeer/coremedia/v1/curated_stage.pb.go
  go/stroeer/coremedia/v1/curation_service.pb.go
  go/stroeer/coremedia/v1/curation_service_grpc.pb.go
  go/stroeer/fragment/v1/stage_service.pb.go
  go/stroeer/fragment/v1/stage_service_grpc.pb.go
  go/stroeer/page/article/v1/article_page.pb.go
  go/stroeer/page/article/v1/article_page_service.pb.go
  go/stroeer/page/article/v1/article_page_service.pb.gw.go
  go/stroeer/page/article/v1/article_page_service_grpc.pb.go
  go/stroeer/page/section/v1/section_page.pb.go
  go/stroeer/page/section/v1/section_page_service.pb.go
  go/stroeer/page/section/v1/section_page_service.pb.gw.go
  go/stroeer/page/section/v1/section_page_service_grpc.pb.go
  go/stroeer/page/stage/v1/stage.pb.go
  stroeer/core/v1/article.proto
  stroeer/core/v1/core_article_service.proto
  stroeer/core/v1/shared.proto
  stroeer/coremedia/v1/curated_stage.proto
  stroeer/coremedia/v1/curation_service.proto
  stroeer/fragment/v1/stage_service.proto
  stroeer/page/article/v1/article_page.proto
  stroeer/page/article/v1/article_page_service.proto
  stroeer/page/section/v1/section_page.proto
  stroeer/page/section/v1/section_page_service.proto
  stroeer/page/stage/v1/stage.proto
Labels: 📖 documentation, 💅 enhancement, ✋ do not merge, 🔄 dependencies, go

#277 ci: use buf gh actions
  .github/workflows/pull-request.yml
  Dockerfile
  java/build.gradle
  java/gradle/wrapper/gradle-wrapper.jar
  java/gradle/wrapper/gradle-wrapper.properties
  java/gradlew
Labels: 💅 enhancement, github_actions

#272 breaking: rename content type OEMBED to EMBED
  stroeer/core/v1/article.proto
Labels: 💥 breaking change, 🎁 API

#288 documentation: aligned ArticlePageService error scenarios to implementation
  .github/workflows/pull-request.yml
  Dockerfile
  Makefile
  go/go.mod
  go/go.sum
  java/build.gradle
  stroeer/core/v1/article.proto
  stroeer/core/v1/core_article_service.proto
  stroeer/coremedia/v1/curation_service.proto
  stroeer/fragment/v1/stage_service.proto
  stroeer/page/article/v1/article_page_service.proto
  stroeer/page/section/v1/section_page_service.proto
  stroeer/page/stage/v1/stage.proto
Labels: 📖 documentation, 🔄 dependencies

#295 chore(node): version bump + tests
  node/__tests__/services.test.ts
  node/package-lock.json
  node/package.json
Labels: 🔄 dependencies

#301 feat!: cleanup of ContentSubType
  stroeer/core/v1/article.proto
Labels: 💥 breaking change, 🎁 API

#302 chore(node): jest
  node/package-lock.json
  node/package.json
Labels: 🔄 dependencies

#279 feat/keywords: include extracted keywords in core.Article
  stroeer/core/v1/article.proto
Labels: 💅 enhancement, 💥 breaking change, 🎁 API
