Repository stroeer/tapir, pull requests merged in 2022-02, with the labels that each got.

#346 chore(go,java,node): bumped dependencies
  Makefile
  README.md
  go/go.mod
  go/go.sum
  java/build.gradle
  java/gradle/wrapper/gradle-wrapper.properties
  node-legacy/package-lock.json
  node-legacy/package.json
  node/package-lock.json
  node/package.json
Labels: 🔄 dependencies, java, javascript, go

#330 breaking: change the body structure
  java/src/test/java/de/stroeer/article/v1/ArticleTest.java
  stroeer/core/v1/article.proto
  stroeer/core/v1/core_article_service.proto
Labels: 💥 breaking change, 🎁 API

#352 chore(node): bump dependencies
  node/package-lock.json
  node/package.json
Labels: 🔄 dependencies, javascript
