Repository stroeer/tapir, pull requests merged in 2022-01, with the labels that each got.

#336 Companions on Articlepages
  stroeer/page/article/v1/article_page.proto
Labels: 🎁 API

#343 chore(node): version bumps
  node-legacy/__tests__/services.test.ts
  node-legacy/package-lock.json
  node-legacy/package.json
  node/__tests__/services.test.ts
  node/package-lock.json
  node/package.json
Labels: 🔄 dependencies, javascript

#345 feat(node): test clients
  .gitignore
  node-legacy/package.json
  node-legacy/src/client.ts
  node-legacy/src/server.ts
  node-legacy/tsconfig.client.json
  node-legacy/tsconfig.json
  node/package.json
  node/src/client.ts
  node/src/server.ts
  node/tsconfig.client.json
  node/tsconfig.json
Labels: javascript

#344 deprecate companions field in ArticlePage and add new method GetArticleCompanions
  node-legacy/__tests__/services.test.ts
  node/__tests__/services.test.ts
  stroeer/page/article/v1/article_page.proto
  stroeer/page/article/v1/article_page_service.proto
Labels: 🎁 API
